# Generated by Django 3.0.2 on 2020-01-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer_system', '0002_userhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
