# Generated by Django 3.0.2 on 2020-01-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer_system', '0003_userhistory_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhistory',
            old_name='data',
            new_name='date',
        ),
    ]
